### ISSUE TITLE
YAMLException when listing drives in Windows

### ISSUE THREAD

**Issue by MistyKuu** [resin-io-modules/drivelist#115]
Hey,
I am getting an exception whenever I try to list drives. Any ideas?

OS: Windows 10 x64.
line: parse.js 89

Uncaught Exception:
YAMLException: bad indentation of a sequence entry at line 8, column 12:
      - path: C:
               ^
    at generateError (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockSequence (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:932:7)
    at composeNode (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1326:12)
    at readBlockMapping (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1057:11)
    at composeNode (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1327:12)
    at readDocument (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1489:3)
    at loadDocuments (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1545:5)
    at load (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1562:19)
    at Object.safeLoad (F:\Projekty\myproject\myproject\node_modules\js-yaml\lib\js-yaml\loader.js:1580:10)

[OK]

**Comment by jviotti** [comment]
Hm, that's weird. YAML is a bit sensitive with spaces/tabs so we could be doing something wrong there. Can you try running the `scripts/win32.bat` in your computer and pasting the whole output here?

**Comment by afandiyusuf** [comment]
i just created pull request for this issue.

**Comment by MistyKuu** [comment]
device: "\\\\.\\PHYSICALDRIVE0"
description: "PLEXTOR PX-128M6S"
size: 128034708480
raw: "\\\\.\\PHYSICALDRIVE0"
system: True
protected: False
mountpoints:
  - path: C:

device: "\\\\.\\PHYSICALDRIVE1"
description: "ASMT 2105 USB Device"
size: 750153761280
raw: "\\\\.\\PHYSICALDRIVE1"
system: True
protected: False
mountpoints:
  - path: D:
  - path: F:

**Comment by jviotti** [comment]
I've released v5.0.1 to npm with this fix.

**Comment by MistyKuu** [comment]
gj, that was quick! I will test that out
