### ISSUE TITLE
YAMLException: incomplete explicit mapping pair

### ISSUE THREAD

**Issue by metachris** [resin-io-modules/drivelist#118]
The current version of drivelist gives me the following error:

    YAMLException: incomplete explicit mapping pair; a key node is missed at line 2, column 14:
        description: :
                     ^
        at generateError (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
        at throwError (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
        at readBlockMapping (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:995:9)
        at composeNode (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
        at readDocument (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
        at loadDocuments (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
        at load (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
        at Object.safeLoad (/myproject/node_modules/drivelist/node_modules/js-yaml/lib/js-yaml/loader.js:1580:10)
        at _.compact._.map (/myproject/node_modules/drivelist/lib/parse.js:89:25)
        at arrayMap (/myproject/node_modules/drivelist/node_modules/lodash/lodash.js:660:23)

It seems that the references version of `js-yaml` is at fault. Any idea?

**Comment by metachris** [comment]
The problem is this drive:

    device: /dev/disk1
    description: :
    size: 249804886016
    mountpoints:
      - path: /
    raw: /dev/rdisk1
    protected: False
    system: True

**Comment by lurch** [comment]
Hmmm, how come your drive has a description of `:`? Do you know if that's a common situation?
Could you paste the output of `diskutil info /dev/disk1` please?

**Comment by metachris** [comment]
This is my standard OSX hard drive:

    $ diskutil info /dev/disk1
       Device Identifier:        disk1
       Device Node:              /dev/disk1
       Whole:                    Yes
       Part of Whole:            disk1
       Device / Media Name:      APPLE SSD SD0256F

       Volume Name:              :

       Mounted:                  Yes
       Mount Point:              /

       File System Personality:  Journaled HFS+
       Type (Bundle):            hfs
       Name (User Visible):      Mac OS Extended (Journaled)
       Journal:                  Journal size 24576 KB at offset 0x19502000
       Owners:                   Enabled

       Content (IOContent):      Apple_HFS
       OS Can Be Installed:      Yes
       Recovery Disk:            disk0s3
       Media Type:               Generic
       Protocol:                 PCI
       SMART Status:             Not Supported
       Volume UUID:              redacted
       Disk / Partition UUID:    redacted

       Total Size:               249.8 GB (249804886016 Bytes) (exactly 487900168 512-Byte-Units)
       Volume Free Space:        13.4 GB (13396934656 Bytes) (exactly 26165888 512-Byte-Units)
       Device Block Size:        512 Bytes
       Allocation Block Size:    4096 Bytes

       Read-Only Media:          No
       Read-Only Volume:         No

       Device Location:          Internal
       Removable Media:          No

       Solid State:              Yes
       Virtual:                  Yes
       OS 9 Drivers:             No
       Low Level Format:         Not supported

       This disk is a Core Storage Logical Volume (LV).  Core Storage Information:
       LV UUID:                  redacted
       LVF UUID:                 redacted
       LVG UUID:                 redacted
       Fusion Drive:             No
       Encrypted:                Yes

**Comment by jviotti** [comment]
Yeah, its very weird. I've tried to simulate this exact same scenario, but `diskutil` won't allow me to set `:` as a name.
