### ISSUE TITLE
Prebuilds failing on Windows

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/drivelist#222]
https://ci.appveyor.com/project/resin-io/drivelist/build/1.0.830/job/k570q7x53q2v79x7

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  code.cc
  log.cc
  drivelist.cc
  com.cc
C:\Users\appveyor\.node-gyp\iojs-1.8.0\deps\v8\include\v8.h(4028): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\drivelist.cc) [C:\projects\drivelist\build\drivelist.vcxproj]
C:\Users\appveyor\.node-gyp\iojs-1.8.0\deps\v8\include\v8.h(4031): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\drivelist.cc) [C:\projects\drivelist\build\drivelist.vcxproj]
C:\Users\appveyor\.node-gyp\iojs-1.8.0\deps\v8\include\v8.h(4104): error C2610: 'v8::WasmModuleObjectBuilder::WasmModuleObjectBuilder(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\drivelist.cc) [C:\projects\drivelist\build\drivelist.vcxproj]
C:\Users\appveyor\.node-gyp\iojs-1.8.0\deps\v8\include\v8.h(4106): error C2610: 'v8::WasmModuleObjectBuilder &v8::WasmModuleObjectBuilder::operator =(v8::WasmModuleObjectBuilder &&)' : is not a special member function which can be defaulted (..\src\drivelist.cc) [C:\projects\drivelist\build\drivelist.vcxproj]
  scanner.cc
  volume.cc
  disk.cc
  wmi.cc
  win_delay_load_hook.cc
prebuild ERR! build error 
prebuild ERR! stack Error: `msbuild` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (C:\projects\drivelist\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! stack     at emitTwo (events.js:125:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:213:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `msbuild` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (C:\projects\drivelist\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! build     at emitTwo (events.js:125:13)
prebuild ERR! build     at ChildProcess.emit (events.js:213:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! drivelist@5.2.0 prebuild: `prebuild --all --strip "-u" "*****"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the drivelist@5.2.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2017-09-28T14_38_40_790Z-debug.log
Command exited with code 2
```

**Comment by jhermsmeier** [comment]
Turns out the issue here is that  VS2013 does not support defaulting move constructor and move assignment operators (see https://github.com/nodejs/node-v8/issues/4).

I have now set the build worker image on AppVeyor to use the VS2015 image (which it should've defaulted to according to the docs) instead of the VS2013 image.
