### ISSUE TITLE
Uncaught TypeError when disk.DeviceNode is not available

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/drivelist#265]
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at transform (/Users/Jonas/Work/etcher/node_modules/drivelist/lib/diskutil.js:99:25)
    at Array.map (native)
    at asyncMap (/Users/Jonas/Work/etcher/node_modules/drivelist/lib/diskutil.js:156:31)
    at next (/Users/Jonas/Work/etcher/node_modules/drivelist/lib/diskutil.js:73:7)
    at ChildProcess.childProcess.spawn.on.on (/Users/Jonas/Work/etcher/node_modules/drivelist/lib/diskutil.js:45:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by lurch** [comment]
Fixed by #266 ?

**Comment by jhermsmeier** [comment]
Yeah

**Comment by jhermsmeier** [comment]
Forgot I made an issue for this :D
